#pragma kernel CSMain

struct DispatchIndirectCommand {
    uint num_groups_x;
    uint num_groups_y;
    uint num_groups_z;
};

struct ArchSegmentData {
    float2 start;
    float2 end;
};

RWTexture2D<float4> path_mask;
float2 path_mask_ws_dims;

// Buffers plats
StructuredBuffer<float4> curve_positions;       // toutes les positions concaténées
StructuredBuffer<uint2> curve_ranges;           // (startIndex, pointCount)
RWStructuredBuffer<ArchSegmentData> segments_buffer;
RWStructuredBuffer<DispatchIndirectCommand> cmds;

int2 WsToPixelCoord(float3 ws_pos, int2 dims) {
    float2 uv = ws_pos.xz / path_mask_ws_dims + 0.5;
    return int2(uv.x * dims.x, uv.y * dims.y);
}

float GetRoadMaskValue(float3 ws_pos, int2 dims) {
    int2 coord = WsToPixelCoord(ws_pos, dims);
    return path_mask[coord].x;
}

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID) {
    int2 dims;
    path_mask.GetDimensions(dims.x, dims.y);

    uint idx = id.x;
    uint2 range = curve_ranges[idx];
    uint start = range.x;
    uint count = range.y;

    if (count < 2) return;

    for (uint i = 0; i < count - 1; i++) {
        float3 p1 = curve_positions[start + i].xyz;
        float3 p2 = curve_positions[start + i + 1].xyz;

        float v1 = GetRoadMaskValue(p1, dims);
        float v2 = GetRoadMaskValue(p2, dims);

        if (v1 > 0 || v2 > 0) {
            uint offset;
            InterlockedAdd(cmds[0].num_groups_x, 1, offset);
            segments_buffer[offset].start = p1.xz;
            segments_buffer[offset].end = p2.xz;
        }
    }
}
