#pragma kernel PathMaskKernel

RWTexture2D<float4> img_output;

float3 Mouse_Position;
float2 path_mask_ws_dims;
bool is_additive;
float Radius;

[numthreads(8, 8, 1)]
void PathMaskKernel(uint3 id : SV_DispatchThreadID)
{
    int2 pixel_coords = int2(id.xy);

    uint width, height;
    img_output.GetDimensions(width, height);
    float2 dims = float2(width, height);

    float2 uv = (float2(pixel_coords) / dims) * path_mask_ws_dims - path_mask_ws_dims / 2.0;
    float2 delta = uv - Mouse_Position.xz;

    float dist = length(delta);


    float brushStrength = smoothstep(Radius, 0.0, dist);

    float4 current = img_output[pixel_coords];

    if (is_additive)
        current.rgb += brushStrength;
    else
        current.rgb -= brushStrength;
    
    current.rgb = saturate(current.rgb);
    img_output[pixel_coords] = float4(current.rgb, 1.0);
}
